# $FreeBSD$

PORTNAME=	retroarch-assets
DISTVERSION=	g20181229
CATEGORIES=	games

MAINTAINER=	greg@unrelenting.technology
COMMENT=	Graphical assets and official branding for RetroArch

LICENSE=	CC-BY-4.0
LICENSE_FILE=	${WRKSRC}/COPYING

USE_GITHUB=	yes
GH_ACCOUNT=	libretro
GH_TAGNAME=	599ffb2375be26ef1

.include <bsd.port.mk>
