# $FreeBSD$

PORTNAME=	libretro-shaders-slang
DISTVERSION=	g20181216
CATEGORIES=	games

MAINTAINER=	greg@unrelenting.technology
COMMENT=	Collection of slang (Vulkan) shaders for libretro

LICENSE=	GPLv3

USE_GITHUB=	yes
GH_ACCOUNT=	libretro
GH_PROJECT=	slang-shaders
GH_TAGNAME=	b54b0b29df42949

.include <bsd.port.mk>
