#!/bin/sh

cd MESA-INTEL

echo "###-Install DEPS-###"  

pkg install -y py37-mako glslang
cd ../graphics/libdrm ; make deinstall reinstall clean ; cd - 

#UnComment For Reinstall
rm -rf mesa-19.3*

wget https://mesa.freedesktop.org/archive/mesa-19.3.2.tar.xz

tar xvpfJ mesa-19.3.2.tar.xz

cd mesa-19.3.2

gpatch -p1 -i ../NEW-PATCH-FREEBSD.diff 
gpatch -p1 -i ../add-disable-tls-support.patch


#this DO SET ld.bfd for linking

mv /usr/bin/ld /usr/bin/ld.llvm
ln -s /usr/local/bin/ld.bfd /usr/bin/ld


#Export Safa Optimizaed Flags And Wno-Error

export CFLAGS="-march=native -mtune=native -O3 -falign-functions=32 -fstrict-aliasing -fomit-frame-pointer -fno-stack-protector -pipe -Wno-error=unused -Wno-error=unused-variable -Wunused -Wno-all -Wno-error -Wno-extra"

export CXXFLAGS="-march=native -mtune=native -O3 -falign-functions=32 -fstrict-aliasing -fomit-frame-pointer -fno-stack-protector -pipe -Wno-error=unused -Wno-error=unused-variable -Wunused -Wno-all -Wno-error -Wno-extra"

export CPPFLAGS="-march=native -mtune=native -O3 -falign-functions=32 -fstrict-aliasing -fomit-frame-pointer -fno-stack-protector -pipe -Wno-error=unused -Wno-error=unused-variable -Wunused -Wno-all -Wno-error -Wno-extra -I/usr/local/include"

export LDFLAGS="-L/usr/local/include"

time meson --buildtype=release --prefix=/usr/local . build -D elf-tls=false -D b_lto=false -D zstd=true -D b_ndebug=true -D platforms=x11,wayland,drm -D dri-drivers=i965 -D gallium-drivers= -D vulkan-drivers=intel -D vulkan-overlay-layer=true -D dri3=true -D egl=true -D llvm=false -D gbm=true -D gles1=false -D gles2=true -D glx=dri -D shared-glapi=true -D valgrind=false -D vulkan=true ; time meson configure build ; time ninja -j3 -v -C build ; time ninja -j3 -v -C build install

cp -Rfa /usr/local/lib/pkgconfig/* /usr/local/libdata/pkgconfig/


#return ld.lld

mv /usr/bin/ld.llvm /usr/bin/ld

cd ../x11-servers/xorg-server ; sh ./COMPILE-XORG-GIT.sh
