# $FreeBSD$

PORTNAME=		libretro-core-info
DISTVERSIONPREFIX=	v
DISTVERSION=		1.7.5
CATEGORIES=		games

MAINTAINER=	greg@unrelenting.technology
COMMENT=	Metadata about libretro cores

LICENSE=	GPLv3

USE_GITHUB=	yes
GH_ACCOUNT=	libretro

.include <bsd.port.mk>
